application: awos-beta
version: 1
runtime: php55
api_version: 1
module: default

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /index.php
  script: index.php
- url: /case.php
  script: case.php
- url: /*.*
  script: index.php
   
  
  